# Generated by Django 5.0.2 on 2024-02-08 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=10)),
                ('cedula', models.CharField(max_length=10)),
                ('ciudad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id_grupo', models.AutoField(primary_key=True, serialize=False)),
                ('detalle', models.CharField(max_length=150)),
                ('comentario', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCliente',
            fields=[
                ('id_detalle_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.CharField(max_length=50)),
                ('fecha_f', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('comentario', models.CharField(max_length=700)),
                ('programa', models.CharField(max_length=500)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lider.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=500)),
                ('detalle_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lider.detallecliente')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=10)),
                ('clave', models.CharField(max_length=50)),
                ('rol', models.CharField(max_length=50)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lider.grupo')),
            ],
        ),
        migrations.AddField(
            model_name='detallecliente',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lider.usuario'),
        ),
        migrations.DeleteModel(
            name='Perro',
        ),
        migrations.DeleteModel(
            name='Refugio',
        ),
    ]
