# Generated by Django 5.0.2 on 2024-02-09 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lider', '0002_cliente_grupo_detallecliente_imagen_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(default='Quito', max_length=50),
        ),
        migrations.AlterField(
            model_name='detallecliente',
            name='comentario',
            field=models.CharField(max_length=700, null=True),
        ),
    ]
